export const stateMapping: Record<string, { code: string; name: string }> = {
  Alabama: { code: "01", name: "Alabama" },
  Alaska: { code: "02", name: "Alaska" },
  Arizona: { code: "04", name: "Arizona" },
  Arkansas: { code: "05", name: "Arkansas" },
  California: { code: "06", name: "California" },
  Colorado: { code: "08", name: "Colorado" },
  Connecticut: { code: "09", name: "Connecticut" },
  Delaware: { code: "10", name: "Delaware" },
  "District of Columbia": { code: "11", name: "District of Columbia" },
  Florida: { code: "12", name: "Florida" },
  Georgia: { code: "13", name: "Georgia" },
  Hawaii: { code: "15", name: "Hawaii" },
  Idaho: { code: "16", name: "Idaho" },
  Illinois: { code: "17", name: "Illinois" },
  Indiana: { code: "18", name: "Indiana" },
  Iowa: { code: "19", name: "Iowa" },
  Kansas: { code: "20", name: "Kansas" },
  Kentucky: { code: "21", name: "Kentucky" },
  Louisiana: { code: "22", name: "Louisiana" },
  Maine: { code: "23", name: "Maine" },
  Maryland: { code: "24", name: "Maryland" },
  Massachusetts: { code: "25", name: "Massachusetts" },
  Michigan: { code: "26", name: "Michigan" },
  Minnesota: { code: "27", name: "Minnesota" },
  Mississippi: { code: "28", name: "Mississippi" },
  Missouri: { code: "29", name: "Missouri" },
  Montana: { code: "30", name: "Montana" },
  Nebraska: { code: "31", name: "Nebraska" },
  Nevada: { code: "32", name: "Nevada" },
  "New Hampshire": { code: "33", name: "New Hampshire" },
  "New Jersey": { code: "34", name: "New Jersey" },
  "New Mexico": { code: "35", name: "New Mexico" },
  "New York": { code: "36", name: "New York" },
  "North Carolina": { code: "37", name: "North Carolina" },
  "North Dakota": { code: "38", name: "North Dakota" },
  Ohio: { code: "39", name: "Ohio" },
  Oklahoma: { code: "40", name: "Oklahoma" },
  Oregon: { code: "41", name: "Oregon" },
  Pennsylvania: { code: "42", name: "Pennsylvania" },
  "Rhode Island": { code: "44", name: "Rhode Island" },
  "South Carolina": { code: "45", name: "South Carolina" },
  "South Dakota": { code: "46", name: "South Dakota" },
  Tennessee: { code: "47", name: "Tennessee" },
  Texas: { code: "48", name: "Texas" },
  Utah: { code: "49", name: "Utah" },
  Vermont: { code: "50", name: "Vermont" },
  Virginia: { code: "51", name: "Virginia" },
  Washington: { code: "53", name: "Washington" },
  "West Virginia": { code: "54", name: "West Virginia" },
  Wisconsin: { code: "55", name: "Wisconsin" },
  Wyoming: { code: "56", name: "Wyoming" },
};
